[tool.poetry]
name = "lectern"
version = "0.23.0"
description = "Literate Minecraft data packs and resource packs."
authors = ["Valentin Berlier <berlier.v@gmail.com>"]
license = "MIT"

homepage = "https://github.com/mcbeet/lectern"
repository = "https://github.com/mcbeet/lectern"
documentation = "https://github.com/mcbeet/lectern"

readme = "README.md"

keywords = [
  "literate-programming",
  "beet",
  "resourcepack",
  "minecraft",
  "datapack"
]

classifiers = ["Framework :: Pytest"]

include = ["lectern/py.typed"]

[tool.poetry.dependencies]
python = "^3.8"
beet = ">=0.68.2"
markdown-it-py = "^2.1.0"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.2"
isort = "^5.10.1"
python-semantic-release = "^7.29.1"
pytest-insta = "^0.1.11"

[tool.poetry.scripts]
lectern = "lectern.cli:main"

[tool.poetry.plugins.pytest11]
lectern = "lectern.pytest_plugin"

[tool.black]
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | node_modules
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"

[tool.semantic_release]
branch = "main"
version_variable = ["lectern/__init__.py:__version__"]
version_toml = "pyproject.toml:tool.poetry.version"
major_on_zero = false
build_command = "poetry build"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
